team = input ("Nennen Sie eine Fußballmannschaft")
team2 = input ("Nennen Sie eine weitere Fußballmannschaft")
präfix = ("gegen")
print(team,präfix,team2)
team3 = input ("Nennen Sie die Punktzahl der ersten Mannschaft")
team4 = input ("Nennen Sie die Punktzahl der zweiten Mannschaft")
print(team,team3,präfix,team2,team4)
